site_name: ABSTRACTS
site_url: https://membranes.github.io/abstracts
site_description: About token classification via the fine tuning of deep learning transformer architectures.

repo_name: membranes.github.io/abstracts
repo_url: https://membranes.github.io/abstracts

copyright: Copyright &copy; Artificial Intelligence Unit

theme:
  name: material
  palette:
    primary: orange

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js