name: Abstracts

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Documentation
    runs-on: ubuntu-latest

    strategy:
      max-parallel: 4
      fail-fast: false
      matrix:
        python-version: [ '3.13' ]

    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout Master
        uses: actions/checkout@v4

      - name : Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f ${{ github.workspace }}/.devcontainer/requirements.txt ]; then pip install -r ${{ github.workspace }}/.devcontainer/requirements.txt; fi

      - name: Deploy
        run : |
          git pull
          mkdocs gh-deploy
